# using google cloud documentations

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT DJ.wsgi

beta_settings:
    cloud_sql_instances: PROJECT_NAME:us-central1:DB_NAME

manual_scaling:
  instances: 1

runtime_config:
  python_version: 3